### ISSUE TITLE
This example lacks VPC and subnet creation 

### ISSUE THREAD

**Issue by aqua0ps** [gruntwork-io/infrastructure-as-code-training#1]
Error applying plan:

1 error(s) occurred:

* aws_security_group.example_rails_app: Error creating Security Group: VPCIdNotSpecified: No default VPC for this user
       	status code: 400, request id: 63262f17-1d3e-4a7b-8f4e-7894597d6e54

**Comment by brikis98** [comment]
To keep the examples in this repo as simple as possible, they assume you have a [default VPC](https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/default-vpc.html) in your AWS account. The error above most likely means you don't have a default VPC, which typically means someone deleted it. You can [contact AWS support](https://aws.amazon.com/premiumsupport/knowledge-center/deleted-default-vpc/) to ask them to put it back.

You could also add Terraform code to create a custom VPC, but it's a fair amount of code (subnets, route tables, gateways, etc) that is more complicated than necessary for the simple examples in this repo.
