### ISSUE TITLE
Fix or remove CircleCI build

### ISSUE THREAD

**Issue by ina-stoyanova** [gruntwork-io/infrastructure-as-code-training#38]
Currently we've got a Github check running the project in CircleCI, but we don't actually have it configured. As part of this issue, we should:
- make a decision if we want a CircleCI pipeline to run - e.g. some terraform validate steps, or some other relevant steps
- if yes, then add a configuration file & make sure it passes
- if no, then disable this check for the project from CircleCI [here](https://app.circleci.com/settings/project/github/gruntwork-io/infrastructure-as-code-training?return-to=https%3A%2F%2Fapp.circleci.com%2Fpipelines%2Fgithub%2Fgruntwork-io%2Finfrastructure-as-code-training%2F14%2Fworkflows%2Ff29271a2-9404-42d2-934b-7b97145ded1c%2Fjobs%2F14)  

**_Why?_**
Currently, almost every PR in this repo is appearing with a broken build because of the missing CircleCI configuration. This is not a big problem, so this task is more a housekeeping type of job.

**Comment by eak12913** [comment]
Closing this issue as completed. I've disabled building this in CircleCI.
